build.gradle, core/src/main/java/com/lastone/core/config/SecurityConfig.java
- SecurityConfig 클래스 작성
- security 관련 빌드 설정
=> feat: spring security 기능 구현

core/src/main/java/com/lastone/core/domain/BaseTime.java, core/src/main/java/com/lastone/core/domain/member/Member.java, core/src/main/java/com/lastone/core/domain/member/MemberRepository.java
BaseTime을 통한 entity 수정 및 생성 시간 자동 입력
=> feat: member entity 및 repository 구현

core/build.gradle, core/src/main/resources/META-INF/spring.factories
[CORE 모듈]
resources/META-INF/ 루트에 spring.factories 파일을 추가했습니다.
querydsl 의존성을 추가했습니다.
=> chore: spring.factories, querydsl 의존성 추가

core/src/main/java/com/lastone/core/domain/chat/ChatMessage.java, core/src/main/java/com/lastone/core/domain/chat/ChatRoom.java, core/src/main/java/com/lastone/core/domain/chat/ChatStatus.java
- Chat Domain 추가
- ChatRoom : builder 패턴과 방 생성할 createChatRoom 메서드 추가
- ChatMessage : 채팅방 내에서의 메세지 doamin 추가
=> feat - Chat Domain 추가

api-server/build.gradle, chatting-server/build.gradle, chatting-server/src/main/java/com/lastone/chat/config/StompConfig.java, core/build.gradle, notification-server/build.gradle
core에 있는 web 의존성 분리
- 채팅 서버는 비동기적으로 움직여야하기 때문에 mvc를 사용하지 않는데, 의존성이 겹치면 꼬일 수 있기 때문에 분리
STOMP 사용하기 위한 설정
- RabbitMQ 사용해서 메세지브로커 구현하기
=> feature - 채팅 설정

chatting-server/src/main/resources/templates/chat/chat.html
- 방번호를 하드코딩 되어있던 것을 URL 에서 가져와 전송하게 수정
=> feature - html 수정

api-server/src/main/java/com/lastone/apiserver/controller/MyPageController.java, api-server/src/main/java/com/lastone/apiserver/controller/TestController.java, api-server/src/main/java/com/lastone/apiserver/exception/MyPageControllerAdvice.java
<한것>
- MyPageController 반환 값에 build() 메서드 누락된 부분 추가
- MyPageControllerAdvice의 안쓰는 import문과 메서드 제거
- 배포시 healthyCheck 작업을 위한 TestController 작성
=> Hotfix/ MyPage 컨트롤러 잘못된 부분 수정

chatting-server/src/main/java/com/lastone/chat/controller/ChatRoomController.java, chatting-server/src/main/java/com/lastone/chat/dto/ChatMessageResDto.java, chatting-server/src/main/java/com/lastone/chat/dto/ChatRoomFindDto.java, chatting-server/src/main/java/com/lastone/chat/dto/ChatRoomResDto.java, chatting-server/src/main/java/com/lastone/chat/persistence/MessageColumn.java, chatting-server/src/main/java/com/lastone/chat/persistence/RoomColumn.java, chatting-server/src/main/java/com/lastone/chat/service/ChatRoomService.java, chatting-server/src/main/java/com/lastone/chat/service/ChatRoomServiceImpl.java, core/src/main/resources/META-INF/spring.factories
- MongoTemplate 를 통한 집계를 위해 Aggregation을 사용.
- 채팅방 목록 조회 로직 작성.
- spring.factories 파일 내용이 있으면 build시 오류가 나기 때문에 내용 삭제
=> 채팅방 목록 가져오기

chatting-server/src/main/java/com/lastone/chat/controller/ChatRoomController.java, core/src/main/java/com/lastone/core/common/response/CommonResponse.java, core/src/main/java/com/lastone/core/common/response/SuccessCode.java
- SuccessCode 추가
- CommonResponse에 deleted 같은 것은 void이기 때문에 메세지만 전달하는 static method 생성
- 채팅방 반환값을 CommonResponse로 수정
=> success code 생성 및 반환값 추가

api-server/src/main/java/com/lastone/apiserver/controller/RecruitmentController.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentService.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentServiceImpl.java, api-server/src/main/java/com/lastone/apiserver/service/s3/S3Service.java, api-server/src/main/java/com/lastone/apiserver/service/s3/S3ServiceImpl.java, core/src/main/java/com/lastone/core/domain/recruitment/PreferGender.java, core/src/main/java/com/lastone/core/domain/recruitment/Recruitment.java, core/src/main/java/com/lastone/core/domain/recruitment/RecruitmentStatus.java, core/src/main/java/com/lastone/core/domain/recruitment/WorkoutPart.java, core/src/main/java/com/lastone/core/domain/recruitment_img/RecruitmentImg.java, core/src/main/java/com/lastone/core/dto/recruitment/Meridiem.java, core/src/main/java/com/lastone/core/dto/recruitment/RecruitmentCreateDto.java, core/src/main/java/com/lastone/core/dto/recruitment/StartedAtDto.java, core/src/main/java/com/lastone/core/repository/recruitment/RecruitmentRepository.java, core/src/main/java/com/lastone/core/repository/recruitment_img/RecruitmentImgRepository.java
<한것>
Recruitment 도메인과 RecruitmentImg 도메인 분리
Recruitment 관련 여러 이미지 등록할 떄 이를 처리할 수 있는 S3 서비스 메서드 구현
Recruitment 관련 도메인 및 Enum 타입 생성
=> Feature/ 모집글 쓰기 api 기능 구현

api-server/src/main/java/com/lastone/apiserver/controller/RecruitmentController.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentService.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentServiceImpl.java, build.gradle, core/src/main/java/com/lastone/core/config/CoreAppConfig.java, core/src/main/java/com/lastone/core/domain/recruitment/Recruitment.java, core/src/main/java/com/lastone/core/domain/recruitment/RecruitmentStatus.java, core/src/main/java/com/lastone/core/dto/recruitment/RecruitmentListDto.java, core/src/main/java/com/lastone/core/dto/recruitment/RecruitmentSearchCondition.java, core/src/main/java/com/lastone/core/repository/recruitment/RecruitmentRepository.java, core/src/main/java/com/lastone/core/repository/recruitment/RecruitmentRepositoryCustom.java, core/src/main/java/com/lastone/core/repository/recruitment/RecruitmentRepositoryImpl.java
<한것> 
LocalDateTime 직렬화 및 역직렬화 빌드 설정
모집글 검색 조건 관련 dto 생성 및 동적 쿼리 작성
모집글 필드 중 title 누락되어서 추가
=> Feature/ 모집글 리스트 가져오는 api 구현

api-server/src/main/java/com/lastone/apiserver/controller/MyPageController.java, api-server/src/main/java/com/lastone/apiserver/controller/RecruitmentController.java, core/src/main/java/com/lastone/core/config/SecurityConfig.java
<한것>
SecurityConfig url 패턴 방식 -> 메서드 어노테이션 검증으로 인증 방식 변경
=> Hotfix/  security 인증 인가 방식 변경

api-server/src/main/java/com/lastone/apiserver/controller/RecruitmentController.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentService.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentServiceImpl.java, core/src/main/java/com/lastone/core/common/response/ErrorCode.java, core/src/main/java/com/lastone/core/common/response/SuccessCode.java, core/src/main/java/com/lastone/core/domain/recruitment/Recruitment.java, core/src/main/java/com/lastone/core/repository/recruitment/RecruitmentRepositoryImpl.java
<한것>
소프트 delete를 위한 entity 칼럼 수정
delete 시 모집글 이미지 파일 정리
모집글 리스트 및 상세 가져올 때 삭제 여부 파악하는 로직 추가
=> Feature/ 모집글 삭제 로직 구현

chatting-server/src/main/java/com/lastone/chat/controller/ChatMessageController.java, chatting-server/src/main/java/com/lastone/chat/controller/ChatRoomController.java, chatting-server/src/main/java/com/lastone/chat/controller/TestChattingController.java, chatting-server/src/main/java/com/lastone/chat/service/ChatRoomServiceImpl.java, chatting-server/src/main/resources/templates/chat/chat.html
- 로컬에서 테스트 할 수 있게 STOMP 분기처리
- chat.html도 로컬 테스트용으로
=> 채팅 보내기 로컬용 수정

api-server/src/main/java/com/lastone/apiserver/controller/RecruitmentController.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentService.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentServiceImpl.java, core/src/main/java/com/lastone/core/dto/recruitment/RecruitmentSearchCondition.java, core/src/main/java/com/lastone/core/repository/recruitment/RecruitmentRepositoryCustom.java, core/src/main/java/com/lastone/core/repository/recruitment/RecruitmentRepositoryImpl.java
<한것>
Page 객체 반환에서 Slice 객체 반환으로 변경
SearchConditionDto에 LastId 추가 (마지막 컨텐츠 id) , 및 필요없는 offset과 size 필드 제거
customRepostiory에서 다음 컨텐츠가 있는지 확인하는 로직 추가
=> Hotfix/ 모집글 리스트 가져오는 방식 무한스크롤 방식으로 변경

api-server/src/main/java/com/lastone/apiserver/controller/ApplymentController.java, api-server/src/main/java/com/lastone/apiserver/service/applyment/ApplymentService.java, api-server/src/main/java/com/lastone/apiserver/service/applyment/ApplymentServiceImpl.java, core/src/main/java/com/lastone/core/common/response/SuccessCode.java, core/src/main/java/com/lastone/core/domain/applyment/Applyment.java, core/src/main/java/com/lastone/core/domain/applyment/ApplymentStatus.java, core/src/main/java/com/lastone/core/domain/recruitment/Recruitment.java, core/src/main/java/com/lastone/core/repository/applyment/ApplymentRepository.java, core/src/main/java/com/lastone/core/repository/recruitment/RecruitmentRepository.java
<한것>
신청 관련 도메인 작성
신청 도메인 작성에 따른 Recruitment Entity 연관관계 매핑 처리
신청 생성 관련 서비스 레이어 작성
신청 생성 관련 컨트롤러 작성
신청 생성 관련 SuccessCode 작성
=> Feature : 신청 생성 관련 기능 구현

api-server/src/main/java/com/lastone/apiserver/controller/RecruitmentController.java, api-server/src/main/java/com/lastone/apiserver/service/matching/MatchingService.java, api-server/src/main/java/com/lastone/apiserver/service/matching/MatchingServiceImpl.java, core/src/main/java/com/lastone/core/common/response/SuccessCode.java, core/src/main/java/com/lastone/core/repository/application/ApplicationRepositoryCustom.java, core/src/main/java/com/lastone/core/repository/application/ApplicationRepositoryImpl.java, core/src/main/java/com/lastone/core/repository/recruitment/RecruitmentRepository.java
<한것>
함께하기 버튼을 누르면 처리 되는 매칭 api 구현
매칭이 된 신청의 상태값은 Sucess로 변경
그 외에 매칭이 되지 않고 Success나 Cancel 상태가 아닌 신청을 Fail로 상태값 변경
=> Feature: 신청 매칭 관련 api 구현

api-server/src/main/java/com/lastone/apiserver/controller/ApplicationController.java, api-server/src/main/java/com/lastone/apiserver/controller/RecruitmentController.java, api-server/src/main/java/com/lastone/apiserver/exception/application/ApplicationControllerAdvice.java, api-server/src/main/java/com/lastone/apiserver/exception/application/ApplicationException.java, api-server/src/main/java/com/lastone/apiserver/exception/application/ApplicationNotEqualRequestIdException.java, api-server/src/main/java/com/lastone/apiserver/exception/application/ApplicationNotFoundException.java, api-server/src/main/java/com/lastone/apiserver/exception/application/ApplicationStatusInCorrectException.java, api-server/src/main/java/com/lastone/apiserver/service/application/ApplicationService.java, api-server/src/main/java/com/lastone/apiserver/service/application/ApplicationServiceImpl.java, api-server/src/main/java/com/lastone/apiserver/service/matching/MatchingService.java, api-server/src/main/java/com/lastone/apiserver/service/matching/MatchingServiceImpl.java, core/src/main/java/com/lastone/core/common/response/ErrorCode.java, core/src/main/java/com/lastone/core/common/response/SuccessCode.java, core/src/main/java/com/lastone/core/domain/application/Application.java, core/src/main/java/com/lastone/core/domain/recruitment/Recruitment.java
<한 것>
요청 받은 신청 취소 관련 로직 구현
요청 한 취소 취소 관련 로직 구현
취소 관련 예외 클래스 생성
=> Feature: 신청 취소 관련 API 구현

api-server/src/main/java/com/lastone/apiserver/exception/token/TokenControllerAdvice.java, api-server/src/main/java/com/lastone/apiserver/service/token/TokenServiceImpl.java, core/src/main/java/com/lastone/core/common/response/ErrorCode.java, core/src/main/java/com/lastone/core/config/SecurityConfig.java, core/src/main/java/com/lastone/core/security/exception/AccessTokenExpiredException.java, core/src/main/java/com/lastone/core/security/exception/CustomTokenException.java, core/src/main/java/com/lastone/core/security/exception/RefreshTokenExpiredException.java, core/src/main/java/com/lastone/core/security/exception/TokenTypeNotEqualException.java, core/src/main/java/com/lastone/core/security/filter/AuthorizationFilter.java, core/src/main/java/com/lastone/core/security/filter/JwtExceptionFilter.java, core/src/main/java/com/lastone/core/security/jwt/JwtExceptionHandler.java, core/src/main/java/com/lastone/core/security/jwt/JwtProvider.java, core/src/main/java/com/lastone/core/security/jwt/TokenHeaderType.java, core/src/main/java/com/lastone/core/security/jwt/TokenType.java
<한것>
토큰 기간 만료시 access토큰과 refresh토큰 분기 예외 처리
API 별로 필요한 토큰 타입이 다를 경우 예외처리
=> Hotfix: 토큰 기간 만료 시 어세스 리프레시 토큰 분기 예외 처리

api-server/src/main/java/com/lastone/apiserver/controller/ApplicationController.java, api-server/src/main/java/com/lastone/apiserver/exception/application/AlreadyAppliedException.java, api-server/src/main/java/com/lastone/apiserver/exception/application/AlreadyMatchingCompleteException.java, api-server/src/main/java/com/lastone/apiserver/exception/application/ApplicantIsEqualToWriterException.java, api-server/src/main/java/com/lastone/apiserver/exception/application/ApplicationControllerAdvice.java, api-server/src/main/java/com/lastone/apiserver/exception/application/ApplyToClosedRecruitmentException.java, api-server/src/main/java/com/lastone/apiserver/service/application/ApplicationServiceImpl.java, core/src/main/java/com/lastone/core/common/response/ErrorCode.java, core/src/main/java/com/lastone/core/domain/recruitment/Recruitment.java, core/src/main/java/com/lastone/core/dto/applicaation/ApplicationDto.java, core/src/main/java/com/lastone/core/dto/applicaation/ApplicationReceivedDto.java, core/src/main/java/com/lastone/core/dto/applicaation/ApplicationRequestedDto.java, core/src/main/java/com/lastone/core/repository/application/ApplicationRepositoryCustom.java, core/src/main/java/com/lastone/core/repository/application/ApplicationRepositoryImpl.java
<한것>
- 신청 생성 시 자신의 모집글이면 신청 안되게 검증
- 신청 생성 시 모집글 상태가 RECRUITING 이 아니면 안되게 검증
- 신청 리스트 반환할 시에 신청 Id도 같이 주는 방식으로 수정
- 동일한 모집글 신청 중복 못하게 검증
- 내가 요청한 신청 취소할때 이미 모집 완료된  상황이면 취소 못하게 구현
=> Hotfix: 신청 로직

chatting-server/src/main/java/com/lastone/chat/service/ChatRoomService.java, chatting-server/src/main/java/com/lastone/chat/service/ChatRoomServiceImpl.java
- 채팅 목록 반환형 List로 수정
- 한꺼번에 모든 채팅방 가져오기 때문에 List로 수정
=> 채팅방 목록 반환형 수정

chatting-server/build.gradle, chatting-server/src/main/java/com/lastone/chat/config/ChatMessageListener.java, chatting-server/src/main/java/com/lastone/chat/config/RabbitMQConfig.java, chatting-server/src/main/java/com/lastone/chat/config/StompConfig.java, chatting-server/src/main/java/com/lastone/chat/controller/ChatMessageController.java, chatting-server/src/main/java/com/lastone/chat/controller/HealthCheckController.java, chatting-server/src/main/java/com/lastone/chat/controller/TestChattingController.java, chatting-server/src/main/java/com/lastone/chat/exception/CannotFoundChatMember.java, chatting-server/src/main/java/com/lastone/chat/service/ChatRoomService.java, chatting-server/src/main/java/com/lastone/chat/service/ChatRoomServiceImpl.java, chatting-server/src/main/resources/templates/chat/chat.html, core/build.gradle, core/src/main/java/com/lastone/core/common/response/ErrorCode.java, core/src/main/java/com/lastone/core/config/SecurityConfig.java, core/src/main/java/com/lastone/core/dto/message/ChatMessageReqDto.java
- 사용자 찾지 못할 때 에러코드 예외 추가
- SecurityConfig permit URL 수정
- RabbitMQ 설정 추가
- RabbitMQ를 이용한 알림 추가
- Health Check URL 수정
=> RabbitMQ를 이용한 메시지 알림 방식 추가

chatting-server/src/main/java/com/lastone/chat/controller/TestChattingController.java, chatting-server/src/main/resources/templates/chat/chat-test.html
- RabbitMQ 설정을 위해서 test 채팅방 새로 생성
=> feature - 테스트 html 추가

api-server/src/main/java/com/lastone/apiserver/service/application/ApplicationServiceImpl.java, api-server/src/main/java/com/lastone/apiserver/service/matching/MatchingServiceImpl.java, core/src/main/java/com/lastone/core/domain/member/Member.java, core/src/main/java/com/lastone/core/domain/notification/Notification.java, core/src/main/java/com/lastone/core/domain/notification/NotificationType.java, core/src/main/java/com/lastone/core/repository/notification/NotificationRepository.java
<한것>
알림 도메인 설계
알림 - 멤버 / 알림 - 모집  연관관계 매핑
매칭 서비스 및 신청 서비스에 알림 생성 관련 로직 추가 작성
=> Feature: 알림 생성 기능 구현

chatting-server/src/main/java/com/lastone/chat/config/ChatMessageListener.java, chatting-server/src/main/java/com/lastone/chat/config/StompConfig.java, chatting-server/src/main/java/com/lastone/chat/controller/ChatMessageController.java, chatting-server/src/main/resources/templates/chat/chat.html
- pattern url 수정
- ec2에서 1:1 채팅방 구독 되는것 최종 확인.
- 채팅방 목록 구독은 인증 정보가 있어야 구독할 수 있기 때문에 추가만 해놓고 조만간 테스트
- allowOrigin 개발 단계에서는 모두 허용
- 생산 주소 추가
=> hotfix - rabbitmq 이슈 해결

api-server/src/main/java/com/lastone/apiserver/constant/ImgTypes.java, api-server/src/main/java/com/lastone/apiserver/controller/MyPageController.java, api-server/src/main/java/com/lastone/apiserver/controller/RecruitmentController.java, api-server/src/main/java/com/lastone/apiserver/exception/global/ImgTypeNotSupportedException.java, api-server/src/main/java/com/lastone/apiserver/exception/mypage/MyPageControllerAdvice.java, api-server/src/main/java/com/lastone/apiserver/exception/recruitment/RecruitmentControllerAdvice.java, api-server/src/main/java/com/lastone/apiserver/oauth2/kakao/KakaoOauth2Service.java, api-server/src/main/java/com/lastone/apiserver/oauth2/kakao/KakaoOauth2UserInfo.java, api-server/src/main/java/com/lastone/apiserver/service/gym/GymServiceImpl.java, api-server/src/main/java/com/lastone/apiserver/service/member/MemberServiceImpl.java, api-server/src/main/java/com/lastone/apiserver/service/mypage/MyPageService.java, api-server/src/main/java/com/lastone/apiserver/service/mypage/MyPageServiceImpl.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentService.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentServiceImpl.java, api-server/src/main/java/com/lastone/apiserver/service/sbd/SbdServiceImpl.java, core/src/main/java/com/lastone/core/common/response/ErrorCode.java, core/src/main/java/com/lastone/core/domain/member/Member.java, core/src/main/java/com/lastone/core/domain/recruitment/Recruitment.java, core/src/main/java/com/lastone/core/dto/mypage/MyPageDto.java, core/src/main/java/com/lastone/core/dto/recruitment/RecruitmentRequestDto.java, core/src/main/java/com/lastone/core/repository/member_gym/MemberGymRepository.java, core/src/main/java/com/lastone/core/repository/recruitment/RecruitmentRepositoryCustom.java, core/src/main/java/com/lastone/core/repository/recruitment/RecruitmentRepositoryImpl.java
[ 작업 내용 ]
- 메서드 1개에 하나의 책임만 갖도록 메서드 분리 작업
- 불명료한 메서드 및 변수명 변경
- for문 람다 활용 방식으로 변경
- 모집글 상세 작성 내용 500글자 -> 100글자 유효성 검증 로직 변경
- 이미지 타입에 대한 검증 로직 추가
- 카카오 로그인 성별 선택 동의에 의한 문제 해결
=> Refactor/ 마이페이지 및 모집글 부문 리팩토링 작업

api-server/src/main/java/com/lastone/apiserver/service/gym/GymServiceImpl.java, api-server/src/main/java/com/lastone/apiserver/service/mypage/MyPageServiceImpl.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentServiceImpl.java, api-server/src/main/java/com/lastone/apiserver/service/sbd/SbdServiceImpl.java, core/src/main/java/com/lastone/core/dto/applicaation/ApplicationRequestedDto.java, core/src/main/java/com/lastone/core/repository/application/ApplicationRepositoryImpl.java, core/src/main/java/com/lastone/core/util/mapper/GenericMapper.java, core/src/main/java/com/lastone/core/util/mapper/GymMapper.java, core/src/main/java/com/lastone/core/util/mapper/MemberMapper.java, core/src/main/java/com/lastone/core/util/mapper/SbdMapper.java
요청한 신청 리스트 관련 데이터에 신청 상태값 추가 작업을 진행하였습니다.
<br/>
프런트에서 신청 관련 로직 처리를 위한 신청 상태 값을 응답데이터에 추가하였습니다.
mapper 관련 클래스를 util 패키지로 이동하였습니다.
<br/>
=> [Fix] : 요청한 신청  데이터에 상태 값 필드 추가 작업

api-server/src/main/java/com/lastone/apiserver/controller/RecruitmentController.java, api-server/src/main/java/com/lastone/apiserver/exception/global/ApiControllerAdvice.java, core/src/main/java/com/lastone/core/domain/recruitment/PreferGender.java, core/src/main/java/com/lastone/core/domain/recruitment/WorkoutPart.java, core/src/main/java/com/lastone/core/dto/recruitment/RecruitmentSearchCondition.java, core/src/main/java/com/lastone/core/util/validator/recruitment/PreferGenderValidator.java, core/src/main/java/com/lastone/core/util/validator/recruitment/RecruitmentDateValidator.java, core/src/main/java/com/lastone/core/util/validator/recruitment/RecruitmentTimeValidator.java, core/src/main/java/com/lastone/core/util/validator/recruitment/ValidatePreferGender.java, core/src/main/java/com/lastone/core/util/validator/recruitment/ValidateWorkoutPart.java, core/src/main/java/com/lastone/core/util/validator/recruitment/WorkoutPartValidator.java
모집글 검색 쿼리스트링에 대한 유효성 검증이 안되는 문제를 해결하였습니다.
현재 기준 이전 날짜에 대한 조회는 유효성 검증에 실패하도록 수정하였습니다.
=> [Fix]: 모집글 검색 쿼리스트링 유효성 검증 로직 작동 안되는 문제 해결

api-server/src/main/java/com/lastone/apiserver/controller/RecruitmentController.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentService.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentServiceImpl.java, core/src/main/java/com/lastone/core/dto/recruitment/RecruitmentIdDto.java, core/src/main/java/com/lastone/core/dto/recruitment/StartedAtDto.java, core/src/main/java/com/lastone/core/util/validator/recruitment/RecruitmentCreateDate.java, core/src/main/java/com/lastone/core/util/validator/recruitment/RecruitmentCreateDateValidator.java
- 모집글 생성 시 날짜 유효성 검증 하는 방식을 모집글 검색과 분리하였습니다.
- 모집글 생성 시 모집글 Id를 반환하는 형식으로 수정하였습니다.
=> [Fix] : 모집글 생성 시 모집글 Id 반환하는 형식으로 변경 및 날짜 유효성 검증 분리

api-server/src/main/java/com/lastone/apiserver/controller/MyPageController.java, api-server/src/main/java/com/lastone/apiserver/service/member/MemberService.java, api-server/src/main/java/com/lastone/apiserver/service/member/MemberServiceImpl.java, api-server/src/main/java/com/lastone/apiserver/service/mypage/MyPageService.java, api-server/src/main/java/com/lastone/apiserver/service/mypage/MyPageServiceImpl.java, core/src/main/java/com/lastone/core/common/response/SuccessCode.java, core/src/main/java/com/lastone/core/dto/gym/GymDto.java, core/src/main/java/com/lastone/core/dto/member/MemberUpdateDto.java, core/src/main/java/com/lastone/core/dto/mypage/MyPageUpdateDto.java, core/src/main/java/com/lastone/core/dto/mypage/NicknameCheckDto.java
- 마이페이지 닉네임 중복 검증 API를 구현하였습니다.
- 마이페이지 수정 시 필수 입력값에 대한 유효성 검증 로직을 추가하였습니다.
=> [Feat]: 마이페이지 닉네임 중복 검증 API 구현 및 필수 입력 값 유효성 검증 로직 추가

api-server/src/main/java/com/lastone/apiserver/ApiServerApplication.java, core/src/main/java/com/lastone/core/dto/recruitment/RecruitmentDetailDto.java, core/src/main/java/com/lastone/core/dto/recruitment/RecruitmentListDto.java
- 날짜 반환시에 시간 앞에 'T' 문자를 공백으로 대체하였습니다.
- 생성 날짜가 한국 날짜 기준 9 시간 뒤로 밀리는 문제를 해결하였습니다.
=> [Fix]: 날짜 반환 형식 변경 및 한국 날짜 기준으로 설정

core/src/main/java/com/lastone/core/dto/applicaation/ApplicationDto.java, core/src/main/java/com/lastone/core/dto/applicaation/ApplicationReceivedDto.java, core/src/main/java/com/lastone/core/dto/applicaation/ApplicationRequestedDto.java, core/src/main/java/com/lastone/core/repository/application/ApplicationRepositoryImpl.java
- 신청 리스트 조회 관련 방식을 DTO -> Entity 방식으로 변경하였습니다. (FetchJoin 활용 및 코드 간결화를 위해) 
- 해당 작업을 통해 받은 신청 및 요청한 신청 관련 리스트 작업에서 쿼리 성능을 최적화하였습니다.
=> [Refactor]: 신청 로직 관련 쿼리 성능 개선

core/src/main/java/com/lastone/core/domain/recruitment/PreferGender.java, core/src/main/java/com/lastone/core/dto/applicaation/ApplicationDto.java, core/src/main/java/com/lastone/core/dto/applicaation/ApplicationReceivedDto.java, core/src/main/java/com/lastone/core/dto/applicaation/ApplicationRequestedDto.java, core/src/main/java/com/lastone/core/dto/partner/TodayPartnerDto.java
- 모집글 선호 성별을 프런트 페이지에 맞게 text 형식을 수정하였습니다 
**(남성 -> 남성만 / 여성 -> 여성만 / 무관 -> 성별무관)**
- 데이터 응답 DTO에 날짜 형식을 수정하였습니다.
(2023.03.23 T 13:00  -> 2023.03.23 13:00)
=> [Fix]: 모집글 선호 성별 text 형식 변경 및 응답 dto 날짜 형식 수정

api-server/src/main/java/com/lastone/apiserver/oauth2/kakao/KakaoOauth2Service.java, core/src/main/java/com/lastone/core/security/jwt/JwtProvider.java, core/src/main/java/com/lastone/core/security/jwt/TokenResponse.java
- 카카오 로그인 시 첫 회원 가입 유무를 파악할 수 있도록 응답 데이터에 isFirstSignUp필드를 추가하였습니다.
=> [Feat]: 회원의 첫 가입 유무를 파악할 수 있도록 하는 기능 구현

api-server/src/main/java/com/lastone/apiserver/controller/RecruitmentController.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentService.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentServiceImpl.java, core/src/main/java/com/lastone/core/common/response/SuccessCode.java, core/src/main/java/com/lastone/core/dto/recruitment/RecruitmentApplyStatusForMember.java
- 모집글 상세에서 회원의 신청 상태 여부 체크를 위한 API 기능을 구현하였습니다.
- isApply 필드명으로 회원이 해당 모집글에 신청하였는지 여부를 파악할 수 있습니다.
=> [Feat]: 모집글 상세에서 신청 상태 체크 파악을 위한 API 기능 구현

api-server/src/main/java/com/lastone/apiserver/constant/ImgTypes.java, api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentServiceImpl.java
- 모집글 이미지 등록 시 이미지 타입 검증 관련 오류를 수정하였습니다.
=> [Fix]: 모집글 이미지 등록 관련 버그 수정

api-server/src/main/java/com/lastone/apiserver/exception/global/ApiControllerAdvice.java, core/src/main/java/com/lastone/core/common/response/ErrorCode.java
- 모집글 및 마이페이지 이미지 등록 시 용량 초과 관련 예외 로직을 추가하였습니다.
=> [Feat]: 이미지 적정 용량 넘어갈 경우 예외 처리 로직 구현

api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentServiceImpl.java, core/src/main/java/com/lastone/core/dto/recruitment/RecruitmentApplyStatusForMember.java
- 모집글 상세에서 신청 여부를 확인할 떄 신청 Id 값을 확인할 수 있도록 기능을 추가하였습니다.
=> [Feat]: 모집글 상세에서 신청Id 확인할수 있는 로직 구현

api-server/src/main/java/com/lastone/apiserver/service/token/TokenServiceImpl.java, scripts/api-server-deploy.sh, scripts/chatting-server-deploy.sh
=> Version Update Content 1.0.5

core/src/main/java/com/lastone/core/domain/member/Member.java, core/src/main/java/com/lastone/core/dto/recruitment/RecruitmentDetailDto.java
- 마이페이지 수정 시 프로필 이미지 값이 Null로 반환되는 문제를 해결하였습니다.
- 프론트 단에서 처리의 편의를 위해 모집글 상세 반환 데이터에 운동 부위 속성값을 추가하였습니다
=> [Fix]: 마이페이지 및 모집글 상세 API 수정

api-server/src/main/java/com/lastone/apiserver/service/recruitment/RecruitmentServiceImpl.java
모집글 업데이트 관련 이미지 유효성 검증 로직을 변경함에 따라 
모집글 작성 시 이미지 관련 처리를 누락하여 생긴 버그 해결
=> [Fix]: 모집글 이미지 등록 관련 버그 해결

core/src/main/java/com/lastone/core/dto/applicaation/ApplicationRequestedDto.java
요청한 신청 리스트에 표시되는 회원 정보를 모집글 작성자로 수정하였습니다.
=> [Fix]: ApplicationRequestedDto toDto 메서드 로직 수정

core/src/main/java/com/lastone/core/repository/application/ApplicationRepositoryImpl.java
FetchJoin 시 Distinct를 명시하여 데이터가 중복되서 반환되는 문제를 해결하였습니다.
=> [Fix] 받은 신청 관련 데이터들이 중복되어 응답되는 문제를 해결하였습니다.

core/src/main/java/com/lastone/core/dto/applicaation/ApplicationDto.java, core/src/main/java/com/lastone/core/repository/application/ApplicationRepositoryImpl.java
applicationId 가 null로 반환되는 문제를 수정하였습니다.
=> Version 1.0.5 Fix Bug
